#!/bin/bash

c=$(for e in lowriter localc loimpress lyx code mate-terminal exit; do
	type "$e" > /dev/null && echo "$e"
done | rofi -dmenu -only-match -p editor -i)
if [ "$c" = "exit" ]; then
	exit
fi
if [ "$1" = "i3" ]; then
	case $c in
		"code") i3_args="--no-startup-id";;
		*);;
	esac
	i3-msg "exec $i3_args $c"
else
	$c & disown
fi
