#!/usr/bin/env -S awk -f
# Pass the path to a tab-separated file of the format:
# display name	executable	test command
# Escape single quotes.

BEGIN {
	FS = "\t"
	sh = "/bin/sh -s"
	name_count = 0
}
{
	if (!$3)
		$3 = "command -v " $1
	if (!$2)
		$2 = $1
	if (last == $1)
		print "elif { " $3 | sh
	else {
		name_count++
		if (NR != 1)
			print "fi" | sh
		print "if { " $3 | sh
	}
	print "} > /dev/null 2>&1; then e" name_count "='" $2 "'; n" name_count "='" $1 "'" | sh
	last = $1
}
END {
	if (last) {
		print "fi" | sh
		ORS = ""
		print "if c=$(printf '%s\\n' " | sh
		for (i = 1; i <= name_count; i++)
			print "$n" i " " | sh
		ORS = "\n"
		gsub(/\/?.*\//, "", FILENAME)
		print "| dmenu -l 10 -fn sans -p '" FILENAME "' -i); then case $c in" | sh
		for (i = 1; i <= name_count; i++)
			print "\"$n" i "\") eval \"$e" i "\" &;;" | sh
		print "*);; esac; fi" | sh
	}
	close(sh)
}
