#!/usr/bin/env python3
import sys
from i3ipc import Connection

if len(sys.argv) > 1:
    del sys.argv[0]
    split = 0
    while split < len(sys.argv) and sys.argv[split][0:2] == '--':
        split += 1
    args = sys.argv[0:split]
    ws = sys.argv[split:]
else:
    print('No arguments provided.', file=sys.stderr)
    exit(1)

i3 = Connection()
i3_ws = i3.get_workspaces()
if '--reverse' in args:
    i3_ws = reversed(i3_ws)
    ws = list(reversed(ws))
    def cmp(x, y): return x < y
else:
    def cmp(x, y): return x > y

try:
    want = ((int(w[:w.index(':')]), w) for w in ws)
    n = next(want)
    first = n
    for workspace in i3_ws:
        if n is None or cmp(workspace.num, n[0]):
            break
        elif n[0] == workspace.num:
            n = next(want, None)
    new_ws = n[1] if n is not None else first[1]
except ValueError:
    print('Each wanted workspace name must have a logical number followed by a colon and visible number.', file=sys.stderr)
    exit(1)
except TypeError:
    print('Improperly formatted arguments.', file=sys.stderr)
    exit(1)

if '--print' in args:
    print(new_ws)
elif '--move' in args:
    i3.command(f'move container to workspace number {new_ws};workspace number {new_ws}')
else:
    i3.command(f'workspace number {new_ws}')
