#!/usr/bin/env python3
from argparse import ArgumentParser
from i3ipc import Connection

parser = ArgumentParser()
parser.add_argument('--reverse', action='store_true')
parser.add_argument('--move', action='store_true')
parser.add_argument('--print', action='store_true')
parser.add_argument('--cmd')
parser.add_argument('--postfix')
args = parser.parse_args()
i3 = Connection()

def done(new_ws):
    if args.print:
        print(new_ws)
    elif args.cmd:
        i3.command(args.cmd.format(new_ws=new_ws))
    elif args.move:
        i3.command(f'move container to workspace number {new_ws};workspace number {new_ws}')
    else:
        i3.command(f'workspace number {new_ws}')

def find_ws():
    all_ws = {1,2,3,4,5,6,7,8,9,10}
    for ws in i3.get_workspaces():
        if args.postfix is not None and args.postfix in ws.name:
            return ws.name
        all_ws.discard(ws.num)
    if args.reverse:
        new_ws = str(max(all_ws))
    else:
        new_ws = str(min(all_ws))
    if args.postfix is not None:
        new_ws += ':' + args.postfix
    return new_ws

done(find_ws())
