#!/usr/bin/env -S gawk -f
@include ".local/lib/dotfiles/misc_scripts/unique_deque.awk"
function load_cache() {
	while ((getline id < stack_file) > 0) deque_push_tail(id)
	close(stack_file)
}
function save_cache() {
	printf("") > stack_file
	p = deque_head
	while (p != -1) {
		print p >> stack_file
		p = deque[p, deque_right]
	}
	close(stack_file)
}
BEGIN {
	stack_file = ENVIRON["XDG_RUNTIME_DIR"] "/rofi_focus_file_stack"
	dm = "i3-msg mode default"
	load_cache()
}
{
	if ($1 == "list") {
		p = deque_tail
		while (p != -1) {
			print p > fifo
			p = deque[p, deque_left]
		}
		print "EOF" > fifo
		close(fifo)
	} else if ($1 == "default") {
		save_cache()
		exit
	} else if ($1 == "close") {
		deque_remove($2)
		count--
	} else if ($1 == "floating") {
		count += $2
	} else if (ignore) {
		if ($1 == "select") {
			ignore = 0
			deque_push($2)
		} else if ($1 == "done") {
			ignore = 0
		}
	} else if ($1 == "focus" || $1 == "select" || $1 == "new") {
		deque_push($2)
	} else if ($1 == "move") {
		ignore = 1
	}
	if (count == 0) {
		printf("") > stack_file
		close(stack_file)
		system(dm); close(dm); exit
	}
}
