#!/usr/bin/env -S gawk -f
@include ".local/lib/dotfiles/misc_scripts/unique_deque.awk"
function load_cache() {
	while ((getline id < stack_file) > 0) deque_push_tail(id)
	close(stack_file)
}
function save_cache() {
	printf("") > stack_file
	p = deque_head
	while (p != -1) {
		print p >> stack_file
		p = deque[p, deque_right]
	}
	close(stack_file)
}
function flush_queue() {
	if (events > 1) {
		if (queue_size == 1) {
			if (deque[queue[0], active]) deque_push(queue[0])
			queue_size = 0
		} else {
			i = 0
			j = queue_size - 1
			while (i < j) {
				if (deque[queue[i], active]) deque_push(queue[i])
				i++
			}
			if (j >= 0) queue_size = 0
		}
	} else if (events == 1) {
		queue_size = 0
	}
}
BEGIN {
	stack_file = ENVIRON["XDG_RUNTIME_DIR"] "/rofi_focus_file_stack"
	dm = "i3-msg mode default"
	queue_size = events = 0
	active = 2
	load_cache()
}
{
	if ($1 == "focus" || $1 == "new") {
		queue[queue_size++] = $2
		deque[$2, active] = 1
		events++
	} else if ($1 == "list") {
		flush_queue()
		p = deque_tail
		while (p != -1) {
			print p > fifo
			p = deque[p, deque_left]
		}
		print "EOF" > fifo
		close(fifo)
	} else if ($1 == "close") {
		remove($2)
		deque[$2, active] = 0
		count--
	} else if ($1 == "default") {
		flush_queue()
		save_cache()
		exit
	} else if ((count += $2) == 0) {
		system(dm); close(dm); exit
	}
}
