#!/bin/sh

if i3-msg -t get_tree | jq '.. | select(.type? == "workspace" and .name != "__i3_scratch") | .floating_nodes | .. | .window_properties? | select('"$1"') | "" | halt_error(1)'; then
	i3-msg -q "$3"
else
	i3-msg -q "[$2 floating] kill"
fi
