#!/bin/sh
ws=$(i3-msg -t get_tree | jq -r 'first(.. | select(.type? == "workspace" and any(.. | .window? == '"$2"'))).name')
mark=$(uuid | awk -vFS= -vmarker="$1" -vmarks="$(i3-msg -t get_marks)" -vws="$ws" '{
	out=marker ws":"$1
	for(i=2;i<=NF;i++)
		if(marks~out)
			out=out$i
		else
			break
	print out
}')
i3-msg -q "[id=$2] mark $mark, floating enable, sticky disable; [con_mark=^$1$ws:.+] move scratchpad, scratchpad show; [id=$2] focus"
