#!/bin/sh

print_windows() {
	echo list > "$XDG_RUNTIME_DIR"/rofi_focus_file_stack.in
	wmctrl -xl | AWKPATH="$HOME" "$HOME"/.local/lib/dotfiles/i3_scripts/rofi_focus_file_print -vignore="$1"
}

if [ -n "$1" ]; then
	case $ROFI_RETV in
		10) i3-msg "[id=$ROFI_INFO] kill" > /dev/null 2>&1; print_windows "$ROFI_INFO";;
		1)  echo "focus $ROFI_INFO" > "$XDG_RUNTIME_DIR"/rofi_focus_file_stack.in
			i3-msg "[id=$ROFI_INFO] focus" > /dev/null 2>&1 &;;
		11) i3-msg '[instance="^caja$" floating] move scratchpad; mode default' > /dev/null 2>&1;;
	esac
else
	if ! i3-msg '[instance="^caja$" floating] move scratchpad, scratchpad show' > /dev/null 2>&1; then
		i3-msg "exec caja" > /dev/null 2>&1
		xdotool search --sync --onlyvisible --classname '^caja$' > /dev/null 2>&1
	fi
	print_windows
fi
exit 0
