#!/bin/sh
rofi -show rff -modes "rff:$HOME/.local/lib/dotfiles/i3_scripts/rofi_focus_file" -matching regex -kb-remove-char-forward Control+d -kb-custom-1 [66] -kb-custom-2 Super_L+f
[ -p "$XDG_RUNTIME_DIR"/rofi_focus_file_stack.in ] && echo done > "$XDG_RUNTIME_DIR"/rofi_focus_file_stack.in
