#!/bin/sh

print_windows() {
	wmctrl -xl | awk -vignore="$1" '
		BEGIN {
			printf("%cprompt%cfolder/file\n", 0, 31)
			printf("%cno-custom%ctrue\n", 0, 31)
			printf("%cuse-hot-keys%ctrue\n", 0, 31)
		}
		$1 != ignore && $2 == "-1" && $3 == "caja.Caja" {
			id = $1
			$1=$2=$3=$4=""
			printf("%s%cinfo%c%s\n", substr($0,5), 0, 31, id)
		}'
}

if [ -n "$1" ]; then
	case $ROFI_RETV in
		10) i3-msg "[id=$ROFI_INFO] kill" > /dev/null 2>&1; print_windows "$ROFI_INFO";;
		1)  i3-msg "[id=$ROFI_INFO] focus" > /dev/null 2>&1 &;;
		11) i3-msg '[instance="^caja$" floating] move scratchpad; mode default' > /dev/null 2>&1;;
	esac
else
	if ! i3-msg '[instance="^caja$" floating] move scratchpad, scratchpad show' > /dev/null 2>&1; then
		i3-msg "exec caja" > /dev/null 2>&1
		xdotool search --sync --onlyvisible --classname '^caja$' > /dev/null 2>&1
	fi
	print_windows
fi
exit 0
