#!/bin/sh

if i3-msg -t get_tree | jq '.. | select(.type? == "workspace" and .name != "__i3_scratch") | .floating_nodes | .. | .window_properties? | select('"$1"') | "" | halt_error(1)'; then
	if ! i3-msg "[$2 floating] move scratchpad, scratchpad show" && [ -n "$3" ]; then
		i3-msg "$3"
	fi
else
	i3-msg "[$2 floating] move scratchpad"
fi
