#!/usr/bin/env bash

gtk_name="--name scratch_calc"
terminal="mate-terminal $gtk_name --disable-factory -e"
calcs="qalculate-gtk R bc calc ipython mate-calc rmaxima octave python qalc sage exit"
calc=$(for c in $calcs; do
	type "$c" > /dev/null && echo "$c"
done | rofi -dmenu -only-match -p "calculator" -i)
case $calc in
	"exit") exit;;
	"qalculate-gtk");&
	"mate-calc")
		calc="$calc $gtk_name";;
	*)  calc="$terminal $calc";;
esac
i3-msg "exec $calc"
