#!/bin/sh
if ids=$(i3-msg -t get_tree | jq -e '[.. | select(.type?=="workspace") | {((.name=="__i3_scratch")|tostring): [.floating_nodes | .. | select('"$1"') | .window]}] | (.[] | .false? // empty | .[]), any(.false? | length > 0)'); then
	i3-msg -q "[$2 floating] move scratchpad"
	echo "$ids" | head -n-1 | xargs -n1 xprop -f _NET_WM_STATE 32a -set _NET_WM_STATE _NET_WM_STATE_SKIP_TASKBAR -id
else
	if ! i3-msg -q "[$2 floating] move scratchpad, scratchpad show, sticky enable" 2> /dev/null && [ -n "$3" ]; then
		i3-msg -q "$3"
	fi
fi
