#!/usr/bin/env python3
import asyncio
import os
import psutil
import re
import signal
from i3ipc import Event
from i3ipc.aio import Connection
from time import sleep


LAUNCHERS = (
    (
        re.compile(r'^(zoom ?|skype|discord|crx_cifhbcnohmdccbgoicgdjpfamggdegmo)$'),
        re.compile(r'^zoom ?$'),
        'exec --no-startup-id timeout 30s "$HOME/.local/lib/dotfiles/misc_scripts/launch" "$HOME/.local/lib/dotfiles/applications/chat"'
    ),
    (
        re.compile(r'^evolution$'),
        None,
        'exec evolution'
    ),
    (
        re.compile(r'^(atril|libreoffice|lyx|code|mate-terminal|chromium|crx_ocdlmjhbenodhlknglojajgokahchlkk)$'),
        None,
        'exec --no-startup-id timeout 30s "$HOME/.local/lib/dotfiles/misc_scripts/launch" "$HOME/.local/lib/dotfiles/applications/office"'
    ),
    (
        re.compile(r'^mate-terminal$'),
        None,
        'exec mate-terminal'
    ),
    (
        re.compile(r'^(Navigator|chromium|netsurf-gtk3|nyxt)$'),
        None,
        'exec gtk-launch "$(xdg-settings get default-web-browser)"'
    ),
    (
        re.compile(r'^(spotify|vlc|rhythmbox|strawberry|audacious|ncspot|ncmpcpp)$'),
        re.compile(r'^mpv$'),
        'exec --no-startup-id timeout 30s "$HOME/.local/lib/dotfiles/misc_scripts/launch" "$HOME/.local/lib/dotfiles/applications/media"'
    )
)
WS_RANGE = range(0, len(LAUNCHERS))


def get_launcher(ws, override=False):
    if ws.num in WS_RANGE:
        launcher = LAUNCHERS[ws.num]
        if override:
            return launcher
        for container in ws:
            if (launcher[0] and container.window_instance and launcher[0].search(container.window_instance)) or (launcher[1] and container.window_class and launcher[1].search(container.window_class)):
                return None
        return launcher
    return None


async def on_workspace_focus(i3, e):
    if launcher := get_launcher(e.current):
        sleep(0.01)
        for ws in await i3.get_workspaces():
            if ws.focused and ws.num != e.current.num:
                return
        await i3.command(launcher[2])


def setup():
    i3 = Connection()
    def quit_handler():
        i3.main_quit()
        exit()
    async def launch_handler():
        for ws in await i3.get_workspaces():
            if ws.focused:
                if launcher := get_launcher(ws, True):
                    await i3.command(launcher[2])
                break
    loop = asyncio.get_event_loop()
    loop.add_signal_handler(signal.SIGINT, quit_handler)
    loop.add_signal_handler(signal.SIGTERM, quit_handler)
    loop.add_signal_handler(signal.SIGUSR1, lambda: asyncio.create_task(launch_handler()))
    i3.on(Event.WORKSPACE_FOCUS, on_workspace_focus)
    return i3


if __name__ == '__main__':
    my_pid = os.getpid()
    try:
        for pid in map(int, os.popen("pgrep -f '" + '.+'.join(psutil.Process(my_pid).cmdline()) + "'")):
            if pid != my_pid:
                os.kill(pid, signal.SIGTERM)
    except ValueError:
        ...
    async def main():
        await (await setup().connect()).main()
    asyncio.run(main())
