#!/bin/sh

if [ p = "$1" ]; then
	regex='^(firefox|Chromium|Brave-browser|Pale moon)$'
	launch_browser () {
		case "$1" in
			"firefox") exec firefox --private-window;;
			"Chromium") exec chromium --incognito;;
			"Brave-browser") exec brave --incognito;;
			"Pale moon") exec palemoon --private-window;;
			*);;
		esac
	}
else
	regex='^(firefox|Chromium|Brave-browser|Pale moon|Nyxt|Netsurf-gtk3)$'
	launch_browser () {
		case "$1" in
			"firefox") exec firefox;;
			"Chromium") exec chromium;;
			"Brave-browser") exec brave;;
			"Pale moon") exec palemoon;;
			"Nyxt") exec nyxt;;
			"Netsurf-gtk3") exec netsurf;;
			*);;
		esac
	}
fi

launch_browser "$(xdotool getwindowfocus getwindowclassname)"
launch_browser "$(i3-msg -t get_tree | jq -r '.. | select(.name?=="4:w:🌐") | .. | .window_properties? // empty | .class | select(test("'"$regex"'")), halt')"
if command -v xdg-open > /dev/null 2>&1; then
	exec xdg-open http://
else
	exec firefox
fi
