#!/bin/sh

case $1 in
	"deploy")
		[ ! -f "$HOME/.Xresources" ] && cp "$DOTFILES_REPO/.local/lib/dotfiles/Xresources" "$HOME/.Xresources" && echo "Created ~/.Xresources"
		[ ! -f "$HOME/.config/autorandr/settings.ini" ] && cp "$DOTFILES_REPO/.local/lib/dotfiles/autorandr-settings.ini" "$HOME/.config/autorandr/settings.ini" && echo "Created ~/.config/autorandr/settings.ini"
		[ -n "$(find /sys/class/power_supply -name 'BAT*')" ] && perl -pi -e 's@#order \+= "battery all"@order \+= "battery all"@' "$HOME/.config/i3status/config" && echo "Battery exists, enabled battery in i3status"
		command -v dconf > /dev/null 2>&1 && dconf load / < "$DOTFILES_REPO/.local/lib/dotfiles/dconf";;

	"update")
		perl -pi -e 's@order \+= "battery all"@#order \+= "battery all"@' "$DOTFILES_REPO/.config/i3status/config";;

	*)
		echo "$1 is not a valid direction."; exit 1;;
esac
exit 0
